{{- range $name, $data := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" $ }}-{{ $name }}
  {{- include "generic.labels" $ | nindent 2 }}
  annotations:
    'helm.sh/hook': pre-install,pre-upgrade
    'helm.sh/hook-weight': '-1'
data: {{ toYaml $data | nindent 2 }}
{{- end }}