{{- if eq .Values.pods.controller "daemonset" -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{ with .Values.pods.labels }}{{ toYaml . | indent 4 }}{{ end }}
  {{- with .Values.pods.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.pods.replicas }}
  replicas: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.pods.strategy }}
  strategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.pods.minReadySeconds }}
  minReadySeconds: {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}
      helm.sh/from: deploy.{{ include "app.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" . }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        helm.sh/chart: {{ include "app.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/from: deploy.{{ include "app.fullname" . }}
{{ with .Values.pods.podLabels }}{{ toYaml . | indent 8 }}{{ end }}
      {{- with .Values.pods.podAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      dnsPolicy: {{ .Values.pods.dnsPolicy }}
      {{- with .Values.pods.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pods.priorityClassName }}
      priorityClassName: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pods.initContainers }}
      initContainers: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "app.name" . }}
          image: "{{ .Values.pods.image.name }}:{{ .Values.pods.image.tag }}"
          imagePullPolicy: {{ .Values.pods.image.pullPolicy }}
          {{- with .Values.pods.command }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.pods.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.pods.env }}
          env: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.pods.envFrom }}
          envFrom: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.pods.volumeMounts }}
          volumeMounts: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.pods.livenessProbe }}
          livenessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.pods.readinessProbe }}
          readinessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          ports: {{ toYaml .Values.pods.ports | nindent 12 }}
          resources: {{ toYaml .Values.pods.resources | nindent 12 }}
{{ with .Values.pods.additionalContainers }}{{ toYaml . | indent 8 }}{{ end }}
      {{- with .Values.pods.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pods.affinity }}
      affinity: {{ toYaml .rules | nindent 8 }}
        {{- if .antiAffinity.enabled }}
          {{- if eq .antiAffinity.type "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: {{ .antiAffinity.topologyKey }}
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ include "app.name" $ }}
                  app.kubernetes.io/instance: {{ $.Release.Name }}
          {{- else if eq .antiAffinity.type "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: {{ .antiAffinity.topologyKey }}
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: {{ include "app.name" $ }}
                    app.kubernetes.io/instance: {{ $.Release.Name }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.pods.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pods.volumes }}
      volumes: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pods.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}