---
apiVersion: v2
name: slack-git-compare
version: 0.0.3
appVersion: v0.1.0
description: Compare git references within Slack
home: https://github.com/mvisonneau/slack-git-compare
sources:
  - https://github.com/mvisonneau/helm-charts/tree/main/charts/slack-git-compare
maintainers:
  - name: mvisonneau
    email: maxime.visonneau@gmail.com
