---
apiVersion: v2
name: gitlab-ci-pipelines-exporter
version: 0.2.15
appVersion: v0.5.3
description: Prometheus / OpenMetrics exporter for GitLab CI pipelines insights
home: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
sources:
  - https://github.com/mvisonneau/helm-charts/tree/main/charts/gitlab-ci-pipelines-exporter
maintainers:
  - name: mvisonneau
    email: maxime.visonneau@gmail.com
dependencies:
  - name: redis
    repository: file://./deps/bitnami/redis/
    version: 14.6.0
    condition: redis.enabled
