---
apiVersion: v1
name: gitlab-ci-pipelines-exporter
version: 0.1.0
appVersion: v0.4.6
description: Prometheus / OpenMetrics exporter for GitLab CI pipelines insights
home: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
sources:
  - https://github.com/mvisonneau/helm-charts/tree/main/charts/gitlab-ci-pipelines-exporter
maintainers:
  - name: mvisonneau
    email: maxime.visonneau@gmail.com
