---
replicas: 1

image:
  repository: docker.io/mvisonneau/tailscale
  pullPolicy: IfNotPresent
  # tag: <default to chart app version>

# Use hostNetwork for the pod
hostNetwork: false

## Additional labels and annotations for the statefulset
##
labels: {}
annotations: {}

## Additional labels and annotations for the pods
podLabels: {}
podAnnotations: {}

## Resources to allocate to the pods
##
resources: {}
#  limits:
#    cpu: 50m
#    memory: 64Mi
#  requests:
#    cpu: 50m
#    memory: 64Mi

## Liveness and Readiness probes
## (not currently configured as I need to figure out what's best to assess, not obvious at first sight)
# livenessProbe:
# readinessProbe:

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
#
nodeSelector: {}

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Set the security context of the pods
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context
##
securityContext:
  capabilities:
    add:
      - NET_ADMIN

## Command to execute
# command:
#   - /usr/local/bin/entrypoint

## Arguments to append to the command
# args:

## Config
config:
  # Authorization key to connect onto tailscale (required)
  authKey: foo

  # Other variables to use during the tailscale up command
  variables: {}
    # eg:
    # TAILSCALE_ACCEPT_DNS: "true"
    # TAILSCALE_ACCEPT_ROUTES: "false"
    # TAILSCALE_ADVERTISE_EXIT_NODES: "false"
    # TAILSCALE_ADVERTISE_ROUTES: 10.0.0.0/8
    # TAILSCALE_ADVERTISE_TAGS: env:prod
    # TAILSCALE_EXIT_NODE: ""
    # TAILSCALE_EXIT_NODE_ALLOW_LAN_ACCESS: "false"
    # TAILSCALE_FORCE_REAUTH: "false"
    # TAILSCALE_HOST_ROUTES: "true"
    # TAILSCALE_HOSTNAME: hostname-override
    # TAILSCALE_LOGIN_SERVER: https://login.tailscale.com
    # TAILSCALE_NETFILTER_MODE: "on"
    # TAILSCALE_SHIELDS_UP: "false"
    # TAILSCALE_SNAT_SUBNET_ROUTES: "true"

# rbac -- If your kubernetes cluster defined the pod security policy, then you need to enable this part, and define clusterRole based on your situation.
rbac:
  enabled: false
  # serviceAccount -- default name of serviceAccount is "default" if you don't define the name by yourself
  serviceAccount:
    name: ""
