---
apiVersion: v2
name: approuvez
version: 0.0.3
appVersion: v0.1.0
description: CLI helper to obtain live confirmation from people over Slack
home: https://github.com/mvisonneau/approuvez
sources:
  - https://github.com/mvisonneau/helm-charts/tree/main/charts/approuvez
maintainers:
  - name: mvisonneau
    email: maxime.visonneau@gmail.com
